config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  resources :items, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.includes(:client)

    respond_to do |format|
      format.html
      format.csv do
        send_data render_to_string, filename: "index.csv", type: :csv
      end
    end
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  private
  def item_params
    params.require(:item).permit(:product, :client_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= link_to '商品登録', new_item_path %>
<%= link_to 'CSV出力', items_path(format: :csv) %>

<div class="contents row">
  <% @items.each do |item| %>
      <p><%= item.product %></p>
      <p><%= item.client.name %></p>
  <% end %>
</div>

app/views/items/new.html.erb
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /商品名と商品説明 %>


    <%# 配送について %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          仕入先
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:client_id, Client.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
      </div>
    </div>
    <%# /配送について %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pulldown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>